"""remove otp email verification fields

Revision ID: 08bfb601873d
Revises: 8e2b2c8b82c5
Create Date: 2026-07-10 06:28:26.062912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08bfb601873d'
down_revision: Union[str, None] = '8e2b2c8b82c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_last_sent_at')
    op.drop_column('users', 'otp_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_last_sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('otp_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
