"""add jingle wizard step4 and reference audio

Revision ID: 2e5d05e15908
Revises: 08bfb601873d
Create Date: 2026-07-10 06:51:23.749392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2e5d05e15908'
down_revision: Union[str, None] = '08bfb601873d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

jingle_status_enum = postgresql.ENUM('DRAFT', 'READY', name='jingle_status')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    jingle_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('reference_audio',
    sa.Column('jingle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jingle_id'], ['jingles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_audio_jingle_id'), 'reference_audio', ['jingle_id'], unique=True)
    op.create_index(op.f('ix_reference_audio_user_id'), 'reference_audio', ['user_id'], unique=False)
    op.add_column(
        'jingles', sa.Column('current_step', sa.Integer(), nullable=False, server_default='1')
    )
    op.add_column(
        'jingles',
        sa.Column(
            'status',
            postgresql.ENUM('DRAFT', 'READY', name='jingle_status', create_type=False),
            nullable=False,
            server_default='DRAFT',
        ),
    )
    op.add_column('jingles', sa.Column('sound_description', sa.String(length=1000), nullable=True))
    op.add_column(
        'jingles', sa.Column('voice_enabled', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.create_index(op.f('ix_jingles_status'), 'jingles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jingles_status'), table_name='jingles')
    op.drop_column('jingles', 'voice_enabled')
    op.drop_column('jingles', 'sound_description')
    op.drop_column('jingles', 'status')
    op.drop_column('jingles', 'current_step')
    op.drop_index(op.f('ix_reference_audio_user_id'), table_name='reference_audio')
    op.drop_index(op.f('ix_reference_audio_jingle_id'), table_name='reference_audio')
    op.drop_table('reference_audio')
    # ### end Alembic commands ###

    jingle_status_enum.drop(op.get_bind(), checkfirst=True)
